version: '3'
services:
    server:
        container_name: 'rajasinga_server'
        build: ./server
        ports:
            - '3001:3001'
        environment:
            - PORT=3001
            - MODE=development
        # networks:
        #     kings_addrs:
        #         ipv4_address: 10.10.1.2
    client:
        container_name: 'rajasinga_client'
        build: ./client
        ports:
            - '3002:3002'
        environment:
            - mode=development
            - PORT=3002
        # networks:
        #     kings_addrs:
        #         ipv4_address: 10.10.1.3
    # proxy:
    #     container_name: 'rajasinga_proxy'
    #     build: ./proxy
    #     ports:
    #         - '80:80'
# networks:
#     kings_addrs:
#         ipam:
#             driver: default
#             config:
#                 - subnet: 10.10.1.1/16
