version: "3.6"
services:
  api:
    container_name: "rajasinga_api"
    build:
      context: ./server
      dockerfile: Dockerfile
      target: prod
    restart: always
    ports:
      - "3001"
    environment:
      - PORT=3001
      - MODE=production
    volumes:
      - ./server:/go/src/github.com/astaphobia/rajasinga/server:rw
      - rajasinga_data:/go/srcgithub.com/astaphobia/rajasinga/server:rw
    networks:
      - raja_network
  client:
    depends_on:
      - api
    container_name: "rajasinga_client"
    build:
      context: ./client
      dockerfile: Dockerfile
      target: prod
    restart: always
    ports:
      - "5001"
    environment:
      - NODE_MODE=production
      - PORT=5001
    volumes:
      - ./client:/rajasinga/client:rw
      - rajasinga_data:/rajasinga/client:rw
    networks:
      - raja_network
  proxy:
    container_name: "rajasinga_proxy"
    build: ./proxy
    restart: always
    volumes:
      - ./proxy:/etc/nginx/conf.d/default.conf
      - rajasinga_data:/etc/nginx/conf.d/default.conf
    networks:
      - raja_network
    links:
      - api:api
      - client:client
    ports:
      - "80:80"

networks:
  raja_network:
    driver: bridge
volumes:
  rajasinga_data:
